typography_spectrum: 0.5266438
color:
  saturation: 0.9254971
  lightness: 0.836253
  brandStrength: 0.678749
  rhythmicContrast: 0.8216391
  brandColors:
    - '#3C493F'
    - '#7E8D85'
    - '#B3BFB8'
    - '#F0F7F4'
    - '#A2E3C4'
layout_spectrum: 0.06980095
author:
  name: Rolf Kosakowski
  email: rolf.kosakowski@KBundB.de
logo: >-
  https://the-grid-user-content.s3-us-west-2.amazonaws.com/95369cf3-3fc8-442f-9d55-b0c26117bac2.jpg
name: Test3000
